using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZooER.Models
{
    // I could let Bridge table be autogenerated by CodeFirst
    // but I need to have nullable FK in it and therefore I
    // defined it explicitly

    public class VisitDrug
    {
       // public int ID { get; set; }
        //[Key]
        //[Column(Order = 1)]
        public int VisitID { get; set; }

        //[Key]
        //[Column(Order = 2)]
        public int DrugID { get; set; }

        public virtual Visit Visit { get; set; }
        public virtual Drug Drug { get; set; }
    }
}
